export const AUTH = 'GALAXY/AUTH/LOGIN';
export const AUTH_SUCCESS = 'GALAXY/AUTH/LOGIN_SUCCESS';
export const AUTH_FAIL = 'GALAXY/AUTH/LOGIN_FAIL';

export const LOGOUT_SUCCESS = 'DR/AUTH/LOGOUT_SUCCESS';
